apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: demo-module
spec:
  organization: vishnu-test-org # replace to your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: this
  module:
    source: "vravind1/s3-simple/aws"
    version: "0.1.0"
  variables:
    - bucket_name: bucket
    - region: region
  workspace:
    name: demo-workspace
