apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: demo-module
spec:
  organization: vishnu-test-org # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: demo-module
  module:
    source: "vravind1/s3-simple/aws"
    version: "0.2.0"
  variables:
    - name: bucket_name
    - name: region
  outputs:
    - name: s3_bucket_arn
  workspace:
    name: demo-workspace
